blank_issues_enabled: false
contact_links:
    - name: ğŸ“ Code of Conduct
      url: https://github.com/aperowebnancy/aperowebnancy-website/blob/main/.github/CODE_OF_CONDUCT.md
      about: â¤ Be nice to other members of the community. â˜® Behave.
